###  LABS
POST http://localhost:3000/admin/create_lab  HTTP/1.1
Content-Type: application/json 

{
    "lab_id": "CL9",
    "lab_name": "firstfloor",
    "lab_incharge": "yashoda",
    "lab_description":"Name"
   
}

###
POST http://localhost:3000/admin/create_stock  HTTP/1.1
Content-Type: application/json 

{
    
    
    "dist_id": "D019",
    "seat_number": "A104",
    "incharge": "yashoda",
    "remarks": "Good condition",
    "stock_type": "Type A",
    "lab_id": "CL1"
  
}

###

POST http://localhost:3000/admin/update_stock  HTTP/1.1
Content-Type: application/json 

{
    
    "stock_id": "5D26RPhzK",
    "dist_id": "D003",
    "seat_number": "A104",
    "incharge": "yashoda updated",
    "remarks": "Good condition",
    "stock_type": "Type A",
    "lab_id": "CL1"
  
}

###

POST http://localhost:3000/admin/delete_stock  HTTP/1.1
Content-Type: application/json 

{
    "stock_id": "dOWKKP7uY"
}


###

POST http://localhost:3000/admin/delete_stock_by_dist_id  HTTP/1.1
Content-Type: application/json 

{
    "dist_id": "D015"
}


### Staff

POST http://localhost:3000/admin/create_staff HTTP/1.1
Content-Type: application/json

{
    
   "staffid": "S000",
    "staffname": "Test C SIr",
    //"distid": "D003",
    "stock_type": "Type A"
    
}

### TimeTable

POST http://localhost:3000/admin/create_timetable HTTP/1.1
Content-Type: application/json

{
    "lab_id": "CL1",
    "subject_id":"IT5506",
    "subject_name": "DBMS Veimala",
    "day": "Monday",
    "session_type": "FN",
    "timings": "9:00 AM - 11:00 AM",
    "subject_teacher": "S000"
}


### Research Scholar

POST http://localhost:3000/admin/create_research_scholar HTTP/1.1
Content-Type: application/json

{
    
    "rs_name": "Srivani",
    "seat_no": "TF10",
    "distid": "D018",
    "tenure": "2024-03-16",
    "staff_id": "S000"
}

### Userlogs

POST http://localhost:3000/admin/create_user_log HTTP/1.1
Content-Type: application/json

{
        
        "labid": "CL1",
        "sysseat": "SF1",
        "distid": "D020",
        "username": "Gogilarasaaaaaaan div",
        "rollno": "2021115037",
        "entry_time": "09:00:00",
        "exit_time": "17:00:00",
        "date": "2024-03-24",
        "timetable_id": "vFN3tIi1y"
}

###

POST http://localhost:3000/admin/create_user_log1 HTTP/1.1
Content-Type: application/json

{
        
    "lab_id": "F1",
    "seat_no": "SF1",
    "name": "Onlyyy log",
    "rollno": "2021115037",
    "entry_time": "09:00:00",
    "date": "2024-03-24"
}
###

POST http://localhost:3000/admin/get_userlog_by_id HTTP/1.1
Content-Type: application/json

{
    "userLogId": 1
}
###


POST http://localhost:3000/admin/get_userlog_by_seatno HTTP/1.1
Content-Type: application/json

{
    "sysseat": "SF1"
}


###

POST http://localhost:3000/admin/get_user_logs_by_lab_id HTTP/1.1
Content-Type: application/json

{
    "labid": "CL1"
}
###


POST http://localhost:3000/admin/delete_userlogs_within_date_range HTTP/1.1
Content-Type: application/json

{
    "startDate": "2024-03-22",
    "endDate": "2024-03-24"
}



### Stocks Depart

POST http://localhost:3000/admin/create_stock_dept HTTP/1.1
Content-Type: application/json

{
    "stockRegisterPageNo": 1,
    "stockRegisterSlNo": 1,
    "description": "kooja Description",
    "bookFigureQuantity": 10,
    "bookStockValueRs": 100,
    "issuedToRemarks": "Issued to Remarks",
    "location": "Location"
}

###
POST http://localhost:3000/admin/create_complaint HTTP/1.1
Content-Type: application/json

{
    
  "complainer_name": "REP",
  "dist_id": "D003",
  "lab_id": "F1"


}
###
POST http://localhost:3000/admin/get_complaint_by_id HTTP/1.1
Content-Type: application/json

{
  "complaintId": "SPtp8Y2jG"
}


###
GET http://localhost:3000/admin/get_all_complaints HTTP/1.1
###
POST http://localhost:3000/admin/get_lab_by_id  HTTP/1.1
Content-Type: application/json 

{
    "labId": "F1"
}

###

POST http://localhost:3000/admin/get_all_labs  HTTP/1.1
Content-Type: application/json 

###

POST http://localhost:3000/admin/update_lab  HTTP/1.1
Content-Type: application/json

{
    "lab_id": "CL1",
    "lab_name": "Kn Laboratory",
    "lab_incharge": "yashoda"
    
}

###

POST http://localhost:3000/admin/delete_lab  HTTP/1.1
Content-Type: application/json

{
    "labId": "CL1"
}


###

POST http://localhost:3000/admin/delete_stock_dept HTTP/1.1
Content-Type: application/json

{
    "deptId": 2
}

###
POST http://localhost:3000/admin/update_stock_dept HTTP/1.1
Content-Type: application/json

{
    "deptId": 1,
    "stockRegisterPageNo": 2,
    "stockRegisterSlNo": 2,
    "description": "Updated Description",
    "bookFigureQuantity": 20,
    "bookStockValueRs": 200,
    "issuedToRemarks": "Updated Issued to Remarks",
    "location": "Updated Location"
}

###

POST http://localhost:3000/admin/get_stock_dept_by_id HTTP/1.1
Content-Type: application/json

{
    "deptId": 1
}

###
GET http://localhost:3000/admin/get_stocks_by_lab_id HTTP/1.1
Content-Type: application/json
###
POST http://localhost:3000/admin/get_stock_by_Labid HTTP/1.1
Content-Type: application/json

{
    "lab_id": "CL1"
}

###

POST http://localhost:3000/admin/get_all_stock_depts HTTP/1.1
Content-Type: application/json


###

POST http://localhost:3000/admin/get_all_stocks HTTP/1.1
Content-Type: application/json



###

POST http://localhost:3000/admin/get_staff_by_id HTTP/1.1
Content-Type: application/json

{
    "staffId": "S009"
}

###

POST http://localhost:3000/admin/get_all_staffs HTTP/1.1
Content-Type: application/json

###

POST http://localhost:3000/admin/update_staff HTTP/1.1
Content-Type: application/json

{
    "staffId": "S009",
    "staffname": "Maha mam"
}

###

POST http://localhost:3000/admin/delete_staff HTTP/1.1
Content-Type: application/json

{
    "staffId": "S009"
}


###

POST http://localhost:3000/admin/get_all_timetables HTTP/1.1
Content-Type: application/json

###

POST http://localhost:3000/admin/get_timetable_by_id HTTP/1.1
Content-Type: application/json

{
    "timetableId": "xym4t4V7o"
}

###

POST http://localhost:3000/admin/update_timetable HTTP/1.1
Content-Type: application/json

{
    "timetable_id": "xym4t4V7o",
    "lab_id": "F1",
    "subject_id": "IT5506",
    "subject_name": "DBMS JAZZMINEEEEEEEEEEEEEE",
    "day": "Monday",
    "session_type": "FN",
    "timings": "9:00 AM - 11:00 AM",
    "subject_teacher": "S003"
}

###

POST http://localhost:3000/admin/delete_timetable HTTP/1.1
Content-Type: application/json

{
    "timetable_id": "pbHGPiBte"
}




###

POST http://localhost:3000/admin/get_all_research_scholars HTTP/1.1
Content-Type: application/json

###


POST http://localhost:3000/admin/get_research_scholar_by_id HTTP/1.1
Content-Type: application/json

{
    "rs_id":"DvkQ8v6up"
}

###

POST http://localhost:3000/admin/update_research_scholar HTTP/1.1
Content-Type: application/json

{
    "rs_id": "DvkQ8v6up",
    "rs_name": "SRivani MAAAAM",
    "seat_no": "A1",
    "tenure": "2024-03-16",
    "distid": "D003",
    "staff_id": "S003"
}

###

POST http://localhost:3000/admin/delete_research_scholar HTTP/1.1
Content-Type: application/json

{
    "scholarId":"DvkQ8v6up"
}


###

DELETE http://localhost:3000/admin/delete_complaint HTTP/1.1
Content-Type: application/json

{
  "complaint_id": "SPtp8Y2jG"
}
###










