const obj ={}
obj.complain = require("./complaints");
obj.lab= require("./labs");
obj.rs= require("./rescholar");
obj.staff = require("./staff");
obj.stock = require("./stocks");
obj.timetable = require("./timetable");
obj.userlog = require("./userlogs");
obj.stockdept = require("./stockdept");
module.exports = obj
