const obj ={}
obj.lab= require("./labs");
obj.rs= require("./rescholar");
obj.staff = require("./staff");
obj.stock = require("./stocks");
obj.timetable = require("./timetable");
obj.Userlog = require("./userlogs");
obj.stockdept = require("./stockdept");
obj.complaint = require("./complaints");
module.exports = obj
